export const GET_SCHEDULES          = 'GET_SCHEDULES';
export const CREATE_SCHEDULE        = 'CREATE_SCHEDULE';
export const UPDATE_SCHEDULE        = 'UPDATE_SCHEDULE';
export const DELETE_SCHEDULE        = 'DELETE_SCHEDULE';

export const ADMIN_GET_SCHEDULES    = 'ADMIN_GET_SCHEDULES';
export const ADMIN_CREATE_SCHEDULE  = 'ADMIN_CREATE_SCHEDULE';
export const ADMIN_UPDATE_SCHEDULE  = 'ADMIN_UPDATE_SCHEDULE';
export const ADMIN_DELETE_SCHEDULE  = 'ADMIN_DELETE_SCHEDULE';
