export const ADD_LOW_CREDIT_NOTIFICATION  = 'ADD_LOW_CREDIT_NOTIFICATION';
export const GET_LOW_CREDIT_NOTIFICATIONS  = 'GET_LOW_CREDIT_NOTIFICATIONS';
export const DELETE_LOW_CREDIT_NOTIFICATION  = 'DELETE_LOW_CREDIT_NOTIFICATION';