export const EMIT_MESSAGE = 'SOCKET_EMIT_MESSAGE';
export const ADD_LISTENER = 'SOCKET_ADD_LISTENER';
export const REMOVE_LISTENER = 'SOCKET_REMOVE_LISTENER';
export const REMOVE_ALL_LISTENERS = 'SOCKET_REMOVE_ALL_LISTENERS';
