export const FLUSH_SCRIPT_NOTIFICATION  = "FLUSH_SCRIPT_NOTIFICATION";
export const OPEN_SCRIPT_NOTIFICATION   = "OPEN_SCRIPT_NOTIFICATION";
export const CLOSE_SCRIPT_NOTIFICATION  = "CLOSE_SCRIPT_NOTIFICATION";
