export const GET_SUBSCRIPTIONS = 'GET_SUBSCRIPTIONS';
export const GET_SUBSCRIPTIONS_ADMIN = 'GET_SUBSCRIPTIONS_ADMIN';
export const UPDATE_SUBSCRIPTION_ADMIN = 'UPDATE_SUBSCRIPTION_ADMIN';
export const DELETE_SUBSCRIPTION_ADMIN = 'DELETE_SUBSCRIPTION_ADMIN';
export const SUBSCRIBE = 'SUBSCRIBE';
